=== RosanaConstantin/pharmacyManagement/src/main/resources/files/farmacie.dtd
<!ELEMENT farmacie (reteta*)>
<!ELEMENT reteta (diagnostic, numarPrescriere, dataEliberarii, medic, pacient, listaMedicamente)>
	<!ATTLIST reteta tip CDATA #REQUIRED>
	<!ATTLIST reteta serie CDATA #REQUIRED>
<!ELEMENT diagnostic EMPTY>
	<!ATTLIST diagnostic cod CDATA #REQUIRED>
<!ELEMENT numarPrescriere (#PCDATA)>
<!ELEMENT dataEliberarii (#PCDATA)>
<!ELEMENT medic (specializare)>
	<!ATTLIST medic nume CDATA #REQUIRED>
<!ELEMENT specializare (#PCDATA)>
<!ELEMENT pacient (nume, sex, cnp, varsta, tipBeneficiar)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT cnp (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT tipBeneficiar (#PCDATA)>
<!ELEMENT listaMedicamente (medicament+)>
<!ELEMENT medicament (denumire, cantitate, compensare, dozaj)>
<!ELEMENT denumire (#PCDATA)>
<!ELEMENT cantitate (#PCDATA)>
<!ELEMENT compensare (#PCDATA)>
<!ELEMENT dozaj (#PCDATA)>

=== RosanaConstantin/pharmacyManagement/src/main/resources/files/s.xml
<?xml-stylesheet version="1.0" type="text/xsl" href="farmacie.xsl"?>
<!DOCTYPE farmacie SYSTEM "farmacie.dtd">

<farmacie>
	<reteta tip="11111" serie="100">
		<diagnostic cod="841"/>
		<numarPrescriere>45</numarPrescriere>
		<dataEliberarii>12.12.2012</dataEliberarii>
		<medic nume="Popescu Ion">
			<specializare>Cardiologie</specializare>
		</medic>
		<pacient>
			<nume>Gheorg121he Vasile</nume>
			<sex>M</sex>
			<cnp>1780202510011</cnp>
			<varsta>40</varsta>
			<tipBeneficiar>salariat</tipBeneficiar>
		</pacient>
		<listaMedicamente>
			<medicament>
				<denumire>Ospen</denumire>
				<cantitate>90</cantitate>
				<compensare>50</compensare>
				<dozaj>2 CPS/zi</dozaj>
			</medicament>
			<medicament>
				<denumire>Ospen</denumire>
				<cantitate>90</cantitate>
				<compensare>50</compensare>
				<dozaj>2 CPS/zi</dozaj>
			</medicament>
			<medicament>
				<denumire>Ospen</denumire>
				<cantitate>90</cantitate>
				<compensare>50</compensare>
				<dozaj>2 CPS/zi</dozaj>
			</medicament>
		</listaMedicamente>
	</reteta>
	<reteta tip="simpla" serie="109">
		<diagnostic cod="193"/>
		<numarPrescriere>90</numarPrescriere>
		<dataEliberarii>30.02.2013</dataEliberarii>
		<medic nume="Vlad Ilie">
			<specializare>Diabetologie</specializare>
		</medic>
		<pacient>
			<nume>Rosana Constantin</nume>
			<sex>F</sex>
			<cnp>2900202510011</cnp>
			<varsta>28</varsta>
			<tipBeneficiar>salariat</tipBeneficiar>
		</pacient>
		<listaMedicamente>
			<medicament>
				<denumire>Ospen</denumire>
				<cantitate>90</cantitate>
				<compensare>50</compensare>
				<dozaj>2 CPS/zi</dozaj>
			</medicament>
			<medicament>
				<denumire>Ospen</denumire>
				<cantitate>90</cantitate>
				<compensare>50</compensare>
				<dozaj>2 CPS/zi</dozaj>
			</medicament>
			<medicament>
				<denumire>Insulina</denumire>
				<cantitate>90</cantitate>
				<compensare>100</compensare>
				<dozaj>1 INJ/zi</dozaj>
			</medicament>
		</listaMedicamente>
	</reteta>
</farmacie>
